[package]
name = "zeth-primitives"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { version = "0.6", default-features = false, features = [
  "rlp",
  "serde",
  "std",
] }
alloy-sol-types = { version = "0.6", optional = true }
alloy-dyn-abi = { version = "0.4", optional = true }
alloy-rlp = { version = "0.3", default-features = false }
alloy-rlp-derive = { version = "0.3", default-features = false }
anyhow = "1.0"
bytes = { version = "1.1", default-features = false }
ethers-core = { version = "2.0", optional = true, features = ["optimism"] }
k256 = { version = "0.13.2", features = [
  "std",
  "ecdsa",
], default_features = false }
revm-primitives = { workspace = true, optional = true, default-features = false }
rlp = "0.5.2"
serde = { version = "1.0", features = ["derive"] }
sha3 = "0.10"
thiserror = "1.0"
once_cell = { version = "1.18", default-features = false, optional = true }
hex = { version = "0.4", features = ["serde"] }
ruint = { version = "1.10", default-features = false }

[dev-dependencies]
bincode = "1.3"
hex-literal = "0.4"
serde_json = "1.0"

[features]
ethers = ["dep:ethers-core"]
revm = ["dep:revm-primitives"]
taiko = [
  "revm-primitives/taiko",
  "dep:alloy-sol-types",
  "dep:alloy-dyn-abi",
  "dep:once_cell",
]
