[workspace]
resolver = "2"
members = [
    "lib",
    "methods",
    "primitives",
    "raiko-guest",
    "raiko-host",
    "sgx-ra",
    "tests/*",
]

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3

[patch.crates-io]
# use optimized risc0 circuit
# ethers-core = {git = "https://github.com/smtmfft/ethers-rs", branch = "ethers-core-2.0.10"}
# ethers-providers = {git = "https://github.com/smtmfft/ethers-rs", branch = "ethers-core-2.0.10"}
# ethers-contract = {git = "https://github.com/smtmfft/ethers-rs", branch = "ethers-core-2.0.10"}
ethers-core = {path = "/home/ubuntu/taiko/references/ethers-rs/ethers-core"}
ethers-providers = {path = "/home/ubuntu/taiko/references/ethers-rs/ethers-providers"}
ethers-contract = {path = "/home/ubuntu/taiko/references/ethers-rs/ethers-contract"}
# c-kzg = {path = "/home/ubuntu/reference/ethereum/c-kzg-4844/bindings/rust"}

# [patch."https://github.com/smtmfft/c-kzg-4844"]
# c-kzg = {path = "/home/ubuntu/reference/ethereum/c-kzg-4844/bindings/rust"}


[workspace.dependencies]
bonsai-sdk = { version = "0.7.0", features = ["async"]}
hashbrown = { version = "0.14", features = ["inline-more"] }
risc0-build = "0.21.0"
risc0-zkvm = { version = "0.21.0", default-features = false }
revm-primitives = { git = "https://github.com/smtmfft/revm.git", branch = "sync-taiko-v3.5", default_features = false }
revm = { git = "https://github.com/smtmfft/revm.git", branch = "sync-taiko-v3.5", default-features = false, features = [
    "serde",
    "taiko"
] }
# reth-primitives = {git = "https://github.com/smtmfft/reth.git", branch = "v0.2.0-beta.2", default-features=false, features = ["c-kzg"]}
c-kzg = {git = "https://github.com/smtmfft/c-kzg-4844", branch = "remove-file-io", default-features = false, features = ["preload-kzg-settings"]}
