name: CI

on:
  push:
    branches: ["main"]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RISC0_VERSION: 0.20.1
  RISC0_TOOLCHAIN_VERSION: test-release-2

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-test-sgx:
    name: Build and test sgx
    runs-on: [self-hosted, linux]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            profile: minimal
      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.6.4
      - name: Install sgx
        run: TARGET="sgx" CI=1 make install
      - name: Build sgx prover
        run: TARGET="sgx" make build
      - name: Test sgx native prover
        run: TARGET="sgx" SGX_DIRECT=1 make test
      - name: Check sgx execution env
        run: |
          cd target/release
          gramine-manifest -Dlog_level=error -Ddirect_mode=0 -Darch_libdir=/lib/x86_64-linux-gnu/ ../../provers/sgx/config/sgx-guest.local.manifest.template sgx-guest.manifest
          gramine-sgx-sign --manifest sgx-guest.manifest --output sgx-guest.manifest.sgx
          gramine-sgx-sigstruct-view sgx-guest.sig
      - name: Test sgx prover
        run: TARGET="sgx" make test
        shell: bash

